<h1>Users </h1>
<br>
<a href="<?php echo $this->url("sonacl-admin/default",array("controller" => "privileges", "action" => "new")); ?>">Novo</a>

<table class="table">
    <tr>
        <th>Id</th>
        <th>Nome</th>
        <th>Resource</th>
        <th>Ação</th>
    </tr>
    <tr>
    <?php foreach ($this->data as $entity): ?>
     <td><?php echo $entity->getRole()->getId(); ?></td>
     <td><?php echo $entity->getNome(); ?></td>
     <td><?php echo $entity->getResource()->getNome(); ?></td>
     <td>
         <a href="<?php echo $this->url('sonacl-admin/default', array('controller' => 'privileges','action' => 'edit', 'id' => $entity->getId()));?>">Edit</a>
     </td>
      <td>
         <a href="<?php echo $this->url('sonacl-admin/default',array('controller' => 'privileges','action' => 'delete','id' => $entity->getId()));?>">Delete</a>
     </td>
     </tr>
    <?php endforeach; ?>
</table>

<?php echo $this->paginationControl($this->data, 'Sliding', 'partial/paginator');
?>
